num1=int(input("enter a number:"))
num2=int(input("enter a number:"))
num3=int(input("entet a number:"))
addition=(num1 + num2)
print("the sum of  num1 and num2 is:",addition)
subraction=(num2-num1)
print("The difference when num2 is subtracted from num1 is:",subraction)
multiplication=(num1*num2)
print( "The product of num1 and num2 is:",multiplication)
division=(num1/num2,num2!=0)
print("The quotient when num1 is divided by num2 is:",division)
modulus=(num1%num2)
remainder= ("The remainder when num1 is divided by num2 is:",modulus)
result=((num1+num2)*num3)/2
print("The result of (num1 + num2) * num3 / 2 is:",result)