a=int(input("enter your name:"))
b=int(input("enter your name:"))
print("sum",a+b)
print("division",a/b)
print("is a greater than b?",a>b)
print("are a and b equal?",a==b)
print("logical AND",a>b and b<a)
print("logical OR",a<b or b>a)